### PR TITLE
Complete first version of raynor

### PR DESCRIPTION
**Pull request by mingrammer**
### Features
1. Run create command (all commands of johanna)
2. Run terminate command (all commands of johanna)
3. Support viewing the command logs in realtime
4. Setting the AWS Configurations
### For next version
1. Make streaming the logs asynchronously. now it is served
   synchronously.
2. Improve the UX for setting the configuration

### CODE REVIEW

**Comment by mingrammer** [comment]
Screenshot (Running the `terminate_all`)

image

**Comment by mingrammer** [comment]
@addnull 

I'll update `README.md` if this PR is merged.

**Review by addnull — CHANGES_REQUESTED** [review]
The VM from Lili does not support Raynor yet.
1. I will add python packages in Lili repo.
2. Raynor should require Redis server. Anything else?

**Comment by mingrammer** [comment]
No. Redis server is only required for raynor (+ python packages in requirements.txt)

**Review by addnull — APPROVED** [review]

**Comment by addnull** [comment]
FYI, I added python packages and update provisioning script in Lili.

**Comment by mingrammer** [comment]
Thank you :)
I'll update README.md soon.

**Pull request merged**
